language: node_js
node_js:
#  - stable
  - "12"
sudo: false
git:
  depth: 1
install:
  - yarn install
cache:
  directories:
    - "$HOME/.npm"
script:
  - yarn lint
  - yarn build

after_success:
  - npm run semantic-release
